# Generated by Django 4.0.4 on 2022-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topic_user_avatar_user_bio_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('borrowed', 'borrowed')], default='available', max_length=32),
        ),
    ]
