# Generated by Django 4.0.4 on 2022-06-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('complete', 'complete')], default='available', max_length=32),
        ),
    ]
